// COURSE: CSCI1620
// TERM: FALL 2020
// 
// NAME: Kyle Reestman
// RESOURCES: No outside resources were used in the creation of this enum.

/////////////////////////////////////////////////
//  DO NOT EDIT THIS FILE.  CHANGING THIS CODE
//  IS NOT REQUIRED BY THE ASSIGNMENT.
/////////////////////////////////////////////////

package snake;

/**
 * A simple type to represent the directions the Snake can travel.
 * 
 * <P>THIS ENUM DEFINITION IS PROVIDED AND SHOULD NOT BE EDITED.
 * 
 * @author kreestman
 *
 */
public enum Direction
{
	/**
	 * Represents the snake moving upwards on the screen.
	 */
	UP,
	
	/**
	 * Represents the snake moving downwards on the screen.
	 */
	DOWN,
	
	/**
	 * Represents the snake moving right on the screen.
	 */
	RIGHT,
	
	/**
	 * Represents the snake moving left on the screen.
	 */
	LEFT;
}
