// COURSE: CSCI1620
// TERM: FALL 2020
// 
// NAME: Kyle Reestman
// RESOURCES: No outside resources were used in the creation of this enum.

/////////////////////////////////////////////////
//  DO NOT EDIT THIS FILE.  CHANGING THIS CODE
//  IS NOT REQUIRED BY THE ASSIGNMENT.
/////////////////////////////////////////////////

package snake;

/**
 * A simple type to represent the possible game states in Snake.
 * 
 * <P>THIS ENUM DEFINITION IS PROVIDED AND SHOULD NOT BE EDITED.
 * 
 * @author kreestman
 *
 */
public enum GameState
{
	/**
	 * Represents when the user has lost the game by allowing the Snake to hit the edge or hit itself.
	 */
	LOST,
	
	/**
	 * Represents when the game is still in progress.
	 */
	PLAYING
}
